

# 2. Create the resource using a loop
resource "google_project_service" "enabled_apis" {
  for_each = toset(var.gcp_service_list)

  project = var.project_id
  service = each.key

  # IMPORTANT: Prevents Terraform from disabling the service 
  # if you remove this resource block or destroy the state.
  disable_on_destroy = false 
}

# Create the Service Account
resource "google_service_account" "promo_agent_sa" {
  account_id   = "promo-agent-sa"
  display_name = "Promo Agent Service Account"
  description  = "Identity for the Promo Agent workload"
  project      = var.project_id
}

# Define the list of Roles
locals {
  promo_agent_roles = [
    "roles/aiplatform.user",                   # Vertex AI User
    "roles/modelarmor.user",                   # Model Armor User
    "roles/run.invoker",                       # Cloud Run Invoker
    "roles/serviceusage.serviceUsageConsumer", # Service Usage Consumer
    "roles/cloudtrace.agent"                   # Cloud Trace Agent
  ]
}

# Bind roles to the Service Account
resource "google_project_iam_member" "sa_permissions" {
  for_each = toset(local.promo_agent_roles)

  project = var.project_id
  role    = each.key
  member  = "serviceAccount:${google_service_account.promo_agent_sa.email}"
}

########################## Weather MCP Server ################################

module "weather_mcp_server" {
  source = "./modules/mcp"

  # Inputs
  project_id   = var.project_id
  region       = var.region
  service_name = "mcp-weather-v1"
  
  # Point to where your python files actually are
  source_dir   = "promo_agent/weather_mcp"
}


module "security" {
  source = "./modules/security"

  project_id = var.project_id
  region     = var.region
}

# 2. Call the new Maps Module
module "maps_setup" {
  source = "./modules/maps"

  project_id = var.project_id
  
  # Pass the SA email so the module can grant it permission
  app_service_account_email = google_service_account.promo_agent_sa.email
  
  # IMPORTANT: Ensure APIs are enabled before trying to create Keys
  depends_on = [google_project_service.enabled_apis]
}

module "storage_setup" {
  source = "./modules/storage"

  project_id = var.project_id
  region     = var.region

  # Pass the email of the SA you created earlier
  service_account_email = google_service_account.promo_agent_sa.email
}

module "network_setup" {
  source = "./modules/network"

  project_id = var.project_id
  region     = var.region
}

module "compute_setup" {
  source = "./modules/compute"

  project_id = var.project_id
  region     = var.region
  zone       = "us-central1-a"

  # Networking Inputs
  network_name = module.network_setup.network_name
  subnet_name  = module.network_setup.subnet_name
  
  # Security Inputs
  service_account_email = google_service_account.promo_agent_sa.email
  secure_tag_value_id   = module.network_setup.secure_tag_value_id

  # Storage Inputs (For Startup Script)
  # We access the specific bucket name from the map output
  code_bucket_name      = module.storage_setup.bucket_details["adk-code"].name
}

module "loadbalancer_setup" {
  source = "./modules/loadbalancer"

  project_id = var.project_id

  # Connect to the Instance Group from the compute module
  instance_group_url = module.compute_setup.instance_group_url
}

# ==============================================================================
# AUTOMATED .env FILE GENERATION
# Writes configuration variables from all modules into a local .env file.
# ==============================================================================
resource "null_resource" "generate_agent_env" {
  # Re-run this block every time any output it depends on changes
  triggers = {
    mcp_url          = module.weather_mcp_server.service_url
    bucket_name      = module.storage_setup.bucket_details["agent-inventory"].name
    ma_req_id        = module.security.promo_req_id
    ma_resp_id       = module.security.promo_resp_id
    project_id       = var.project_id
    region           = var.region
  }

  provisioner "local-exec" {
    command = <<-EOT
      # Define the target directory relative to the root module
      ENV_DIR="${path.module}/promo_agent/multi_agent"
      
      # Ensure the directory exists
      mkdir -p $ENV_DIR

      # Write the .env file content
      cat > "$ENV_DIR/.env" <<EOF
# --- Generated by Terraform ---
# WARNING: DO NOT COMMIT THIS FILE IF IT CONTAINS LIVE SECRETS
GOOGLE_GENAI_USE_VERTEXAI=TRUE
GOOGLE_CLOUD_PROJECT=${var.project_id}
GOOGLE_CLOUD_LOCATION=${var.region}
MCP_URL="${module.weather_mcp_server.service_url}/mcp/"
MCP_AUD="${module.weather_mcp_server.service_url}"
MAPS_SECRET_ID="${module.maps_setup.secret_resource_id}"
MAPS_SECRET_VERSION="latest"
INVENTORY_BUCKET_NAME="${module.storage_setup.bucket_details["agent-inventory"].name}"
MODEL_ARMOR_ENDPOINT="modelarmor.${var.region}.rep.googleapis.com"
MA_REQUEST_TEMPLATE_ID="${module.security.promo_req_id}"
MA_RESPONSE_TEMPLATE_ID="${module.security.promo_resp_id}"
GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY="true"
OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT="true"
EOF
      echo ".env file created at $ENV_DIR/.env"
    EOT
  }

  # This ensures the .env file is only written after all modules have created
  # their resources and produced their output values.
  depends_on = [
    module.weather_mcp_server,
    module.maps_setup,
    module.security,
    module.storage_setup,
  ]
}
/*
module "vertex_deploy" {
  source = "./modules/vertex_deploy"

  project_id = var.project_id
  region     = var.region
  
  # Point to your folder structure
  agent_source_path = "promo_agent/multi_agent"

  # ---------------------------------------------------------
  # DEPENDENCY CHAINING
  # We use the ID of the env-generation resource to force order
  # ---------------------------------------------------------
  dependency_signal = null_resource.generate_agent_env.id
}

### UI ####
# 1. Wait for deployment to finish
resource "time_sleep" "wait_for_engine" {
  create_duration = "30s"
  depends_on      = [module.vertex_deploy]
}

# ⚠️ AUTOMATION CHALLENGE:
# Terraform cannot natively "read" the output of the python script we ran.
# WORKAROUND: We will assume you paste the ID, OR we use a script to find it.
# Below uses an 'external' data source to fetch the latest ID via gcloud.

#data "external" "latest_engine_id" {
#  program = ["bash", "-c", "gcloud beta ai agent-engines list --region=${var.region} --project=${var.project_id} --sort-by='~creationTimestamp' --limit=1 --format='json(name)' | jq '.[0]'"]
  
#  depends_on = [time_sleep.wait_for_engine]
#}
*/

/*
# 3. Deploy the UI
module "agent_ui" {
  source = "./modules/agent_ui"

  project_id = var.project_id
  region     = var.region
  
  # Pass the ID fetched from the script
  reasoning_engine_resource_name = var.latest_engine_id #data.external.latest_engine_id.result.name
  #depends_on = [time_sleep.wait_for_engine]
}
*/
####### Gemini Enterprise #########
# 1. Deploy the Agent Identity
module "agent_registry" {
  source     = "./modules/agent_registry"
  project_id = var.project_id
}

# 2. Run the Python Script to Link them
resource "null_resource" "register_gemini_integration" {
  #triggers = {
  #  deployment_signal = module.vertex_deploy.deployment_complete_id
  #}

  provisioner "local-exec" {
    environment = {
      TF_PROJECT_ID       = var.project_id
      TF_REGION           = var.region
      AGENT_ID            = module.agent_registry.agent_id
      
      # IMPORTANT: We need the ID of the engine we deployed.
      # If you don't have a clean output for this, use the data source or manual ID.
      # REASONING_ENGINE_ID = "projects/123.../locations/us-central1/reasoningEngines/456..."
      # OR better, use the variable if you hardcoded it previously:
      #REASONING_ENGINE_ID = "projects/308005744996/locations/us-central1/reasoningEngines/5409258559076564992"
      #"projects/308005744996/locations/us-central1/reasoningEngines/528482462913789952"
    }

    command = <<EOT
      e# 1. Clean Start
      rm -rf .reg_venv
      python3 -m venv .reg_venv
      source .reg_venv/bin/activate
      
      # 2. Install
      pip3 install --quiet --upgrade pip3
      pip3 install --upgrade google-cloud-discoveryengine google-cloud-aiplatform requests google-auth
      
      # 3. Run Script
      python register_tool.py
    EOT
  }
  
  depends_on = [module.agent_registry]
}